export const allPackages = [
  { 
    id: '1', 
    title: 'SKY LUXURY', 
    price: '$2,499', 
    img: 'https://images.unsplash.com/photo-1436491865332-7a61a109c0f3?auto=format&fit=crop&q=80&w=800', 
    departure: 'New York', 
    arrival: 'London',
    duration: '7 Days',
    rating: 4.9,
    reviews: 128,
    description: 'Experience the ultimate luxury in the sky. Our premium package includes first-class travel, 5-star accommodation, and exclusive access to private lounges and events in both New York and London.',
    inclusions: ['First Class Flights', '5-Star Hotel Stay', 'Private Transfers', 'Gourmet Dining', 'City Tours']
  },
  { 
    id: '2', 
    title: 'CLOUD NINE', 
    price: '$1,899', 
    img: 'https://images.unsplash.com/photo-1540339832862-47452993c66e?auto=format&fit=crop&q=80&w=800', 
    departure: 'Paris', 
    arrival: 'Tokyo',
    duration: '10 Days',
    rating: 4.8,
    reviews: 95,
    description: 'A perfect blend of European charm and Asian innovation. Journey from the romantic streets of Paris to the neon-lit skyscrapers of Tokyo with our curated travel experience.',
    inclusions: ['Business Class Flights', 'Boutique Hotels', 'Cultural Workshops', 'Guided Tours', 'Local Cuisine Tasting']
  },
  { 
    id: '3', 
    title: 'HORIZON PLUS', 
    price: '$3,299', 
    img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800', 
    departure: 'Dubai', 
    arrival: 'Maldives',
    duration: '12 Days',
    rating: 5.0,
    reviews: 210,
    description: 'The ultimate tropical escape. Start with the opulence of Dubai before heading to the pristine beaches of the Maldives for a truly unforgettable vacation.',
    inclusions: ['Private Jet Experience', 'Overwater Villa', 'Desert Safari', 'Snorkeling & Diving', 'Spa Treatments']
  },
  { 
    id: '4', 
    title: 'OCEAN BREEZE', 
    price: '$2,199', 
    img: 'https://images.unsplash.com/photo-1506929199175-60933429172b?auto=format&fit=crop&q=80&w=800', 
    departure: 'Miami', 
    arrival: 'Bahamas',
    duration: '5 Days',
    rating: 4.7,
    reviews: 156,
    description: 'Short but sweet. Enjoy the vibrant energy of Miami followed by the relaxing turquoise waters of the Bahamas. Perfect for a quick getaway.',
    inclusions: ['Luxury Cruise', 'Beachfront Resort', 'Water Sports', 'Nightlife Access', 'Island Hopping']
  },
  { 
    id: '5', 
    title: 'MOUNTAIN HIGH', 
    price: '$1,599', 
    img: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800', 
    departure: 'Denver', 
    arrival: 'Swiss Alps',
    duration: '8 Days',
    rating: 4.6,
    reviews: 82,
    description: 'For the adventure seekers. From the Rockies to the Alps, this package offers the best skiing and hiking experiences in the world.',
    inclusions: ['Premium Flights', 'Mountain Lodges', 'Ski Passes', 'Hiking Guides', 'Equipment Rental']
  },
  { 
    id: '6', 
    title: 'URBAN ESCAPE', 
    price: '$2,799', 
    img: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&q=80&w=800', 
    departure: 'London', 
    arrival: 'Singapore',
    duration: '9 Days',
    rating: 4.8,
    reviews: 114,
    description: 'Explore two of the world\'s most dynamic cities. A journey that takes you from the historic landmarks of London to the futuristic gardens of Singapore.',
    inclusions: ['Direct Flights', 'Luxury City Hotels', 'Fine Dining', 'Museum Access', 'Private City Guide']
  },
];
